runtime: python39 # Specifies the Python runtime version

entrypoint: gunicorn -b :$PORT main:app # Command to start your Flask API

handlers:
  - url: /.* # Routes all requests to your Flask API
    script: auto
